"""
Google OAuth Token Generator for Google Meet Integration
Run this script to get your GOOGLE_MEET_ACCESS_TOKEN and GOOGLE_MEET_REFRESH_TOKEN
"""

import os
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
import pickle

# Scopes required for Google Calendar and Meet
SCOPES = [
    'https://www.googleapis.com/auth/calendar',
    'https://www.googleapis.com/auth/calendar.events'
]

def get_google_oauth_token():
    """
    Get Google OAuth tokens using installed app flow
    This will open a browser for you to authorize the app
    """
    
    # Check if we have .env file
    if not os.path.exists('.env'):
        print("❌ .env file not found in backend2/ directory!")
        return
    
    # Load client credentials from .env
    from dotenv import load_dotenv
    load_dotenv()
    
    client_id = os.getenv('GOOGLE_CLIENT_ID')
    client_secret = os.getenv('GOOGLE_CLIENT_SECRET')
    
    if not client_id or not client_secret:
        print("❌ GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET not found in .env")
        print("Please add them first!")
        return
    
    print("✅ Found Google credentials in .env")
    print(f"Client ID: {client_id[:20]}...")
    print("\n📋 IMPORTANT: Add this redirect URI to Google Cloud Console:")
    print("   http://localhost:8080/")
    print("\n   Go to: https://console.cloud.google.com/apis/credentials")
    print("   Edit your OAuth 2.0 Client ID")
    print("   Add 'http://localhost:8080/' to 'Authorized redirect URIs'")
    print("   Click Save\n")
    
    input("Press Enter after you've added the redirect URI to continue...")
    
    print("\n🔐 Starting OAuth flow...\n")
    
    # Create client config - use localhost:8080/ (trailing slash required by run_local_server)
    redirect_uri = "http://localhost:8080/"
    
    client_config = {
        "installed": {
            "client_id": client_id,
            "client_secret": client_secret,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": [redirect_uri]
        }
    }
    
    creds = None
    
    # Check if we have saved token
    if os.path.exists('google_token.pickle'):
        print("📦 Found saved token, loading...")
        with open('google_token.pickle', 'rb') as token:
            creds = pickle.load(token)
    
    # If no valid credentials, let user log in
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("🔄 Token expired, refreshing...")
            creds.refresh(Request())
        else:
            print("🌐 Opening browser for authorization...")
            print("Please sign in with your Google account and authorize the app")
            print("\n⚠️  If browser doesn't open, copy paste the URL from terminal\n")
            
            flow = InstalledAppFlow.from_client_config(
                client_config,
                scopes=SCOPES,
                redirect_uri=redirect_uri
            )
            
            creds = flow.run_local_server(port=8080, open_browser=True)
        
        # Save the credentials for next time
        with open('google_token.pickle', 'wb') as token:
            pickle.dump(creds, token)
        
        print("✅ Token saved to google_token.pickle")
    
    # Display tokens
    print("\n" + "="*70)
    print("🎉 SUCCESS! Copy these values to your .env file:")
    print("="*70)
    print(f"\nGOOGLE_MEET_ACCESS_TOKEN={creds.token}")
    if creds.refresh_token:
        print(f"GOOGLE_MEET_REFRESH_TOKEN={creds.refresh_token}")
    print("\n" + "="*70)
    
    # Optionally write to .env
    response = input("\n📝 Would you like to automatically add these to your .env file? (y/n): ")
    if response.lower() == 'y':
        with open('.env', 'a') as f:
            f.write(f"\n# Google Meet OAuth Tokens (Generated by get_google_token.py)\n")
            f.write(f"GOOGLE_MEET_ACCESS_TOKEN={creds.token}\n")
            if creds.refresh_token:
                f.write(f"GOOGLE_MEET_REFRESH_TOKEN={creds.refresh_token}\n")
        print("✅ Tokens added to .env file!")
        print("⚠️  Note: Access tokens expire after 1 hour. Use refresh token to get new ones.")
    else:
        print("📋 Please manually copy the tokens to your .env file")
    
    print("\n🚀 You can now use Google Meet auto-generation in interview scheduling!")


if __name__ == "__main__":
    try:
        get_google_oauth_token()
    except Exception as e:
        print(f"\n❌ Error: {e}")
        print("\nTroubleshooting:")
        print("1. Make sure google-auth-oauthlib is installed: pip install google-auth-oauthlib")
        print("2. Check that GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET are correct in .env")
        print("3. Ensure port 8080 is not in use")
